### ISSUE TITLE
No life...

### ISSUE THREAD

**Issue by rockcat** [tebl/RC6502-Apple-1-Replica#3]
Hi
Are there any known issues with your rev F board?
I've built one but there's no sign of life. All soldering looks ok but I may just have a short somewhere...

Thanks
![IMG_20190923_224540082](https://user-images.githubusercontent.com/2271227/65465574-93373a00-de54-11e9-96cb-a061fc4f0fd1.jpg)
![IMG_20190923_224552503](https://user-images.githubusercontent.com/2271227/65465576-93373a00-de54-11e9-9f70-38f5f33b0a10.jpg)

**Comment by rockcat** [comment]
HI
Found the problem - a dodgy capacitor - replaced it and now no short.
Next problem is that I  am getting millions of newlines thrown at me.

Also, do you have the source code of the ROM?

Thanks

**Comment by rockcat** [comment]
All working now :)
My 7400 had got fried.
Thanks for the PCB design !

**Comment by tebl** [comment]
Been sick a while, so I didn't notice the ticket - glad to see you got it working. Never imagined the 6522 working directly without changes though, so that's new :-)

I used the ROM contents out of the Ben Heck project (https://github.com/thebenheckshow/158-tbhs-apple-1-replica/tree/master/software/code), it also has the source file. That project never had any hardware documentation, which is where mine got started to fill the gaps and have fun along the way.
